name: Developer Workflow Automation

on:
  pull_request:
    types:
      - opened
      - closed
  create:
    branches:
      - '*'

jobs:
  manage-project-card:
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Card Creation on Branch
        if: github.event_name == 'create' && github.event.ref_type == 'branch'
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const branchName = context.payload.ref;
            const projects = await github.rest.projects.listForOrg({
              org: context.repo.owner
            });
            
            const project = projects.data.find(p => p.name === 'A11Y');
            
            if (project) {
              const columns = await github.rest.projects.listColumns({
                project_id: project.id
              });
              
              const inProgressColumn = columns.data.find(c => c.name.toLowerCase() === 'in progress');
              
              if (inProgressColumn) {
                await github.rest.projects.createCard({
                  column_id: inProgressColumn.id,
                  note: `A11Y iniciado: ${branchName} por @${context.actor}`
                });
              }
            }

      - name: Move to Done on PR Merge
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prTitle = context.payload.pull_request.title;
            const prAuthor = context.payload.pull_request.user.login;
            const projects = await github.rest.projects.listForOrg({
              org: context.repo.owner
            });
            
            const project = projects.data.find(p => p.name === 'A11Y');
            
            if (project) {
              const columns = await github.rest.projects.listColumns({
                project_id: project.id
              });
              
              const doneColumn = columns.data.find(c => c.name.toLowerCase() === 'done');
              
              if (doneColumn) {
                await github.rest.projects.createCard({
                  column_id: doneColumn.id,
                  note: `A11Y completado: ${prTitle} por @${prAuthor}`
                });
              }
            }
