name: Project Automation

on:
  create:
    branches:
      - '*'
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened

jobs:
  create_todo:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch'
    steps:
      - name: Add item to To Do
        uses: octokit/graphql-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          query: |
            mutation {
              addProjectV2ItemById(input: {
                projectId: "PVT_kwHOBx68XM4Awl1F",
                contentId: "R_kgDOMl60tQ",
                fieldValues: [
                  {fieldId: "f75ad846", value: "To Do"}
                ]
              }) {
                item {
                  id
                }
              }
            }

  move_to_progress:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Move item to In Progress
        uses: octokit/graphql-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          query: |
            mutation {
              updateProjectV2ItemFieldValue(input: {
                projectId: "PVT_kwHOBx68XM4Awl1F",
                itemId: "ITEM_ID",
                fieldId: "47fc9ee4",
                value: "In Progress"
              }) {
                clientMutationId
              }
            }

  move_to_done:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Move item to Done
        uses: octokit/graphql-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          query: |
            mutation {
              updateProjectV2ItemFieldValue(input: {
                projectId: "PVT_kwHOBx68XM4Awl1F",
                itemId: "ITEM_ID",
                fieldId: "98236657",
                value: "Done"
              }) {
                clientMutationId
              }
            }
