name: Developer Workflow Automation

on:
  pull_request:
    types:
      - opened
      - closed
  push:
    branches:
      - 'dev'
      - 'main'

permissions:
  contents: read
  projects: write

jobs:
  manage-project-card:
    runs-on: ubuntu-latest
    steps:
      - name: Move PR to In Progress
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const projects = await github.rest.projects.listForOrg({
              org: context.repo.owner
            });
            
            const project = projects.data.find(p => p.name === 'A11Y');
            
            if (project) {
              const columns = await github.rest.projects.listColumns({
                project_id: project.id
              });
              
              const inProgressColumn = columns.data.find(c => c.name.toLowerCase() === 'in progress');
              
              if (inProgressColumn) {
                await github.rest.projects.createCard({
                  column_id: inProgressColumn.id,
                  note: `PR Abierto: ${context.payload.pull_request.title} por @${context.payload.pull_request.user.login}`
                });
              }
            }

      - name: Move PR to Done
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const projects = await github.rest.projects.listForOrg({
              org: context.repo.owner
            });
            
            const project = projects.data.find(p => p.name === 'A11Y');
            
            if (project) {
              const columns = await github.rest.projects.listColumns({
                project_id: project.id
              });
              
              const doneColumn = columns.data.find(c => c.name.toLowerCase() === 'done');
              
              if (doneColumn) {
                await github.rest.projects.createCard({
                  column_id: doneColumn.id,
                  note: `PR Completado: ${context.payload.pull_request.title} por @${context.payload.pull_request.user.login}`
                });
              }
            }
